# Generated by Django 4.2.23 on 2025-06-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(default='Unnamed Device', max_length=255)),
                ('model', models.CharField(default='Unknown', max_length=100)),
                ('status', models.CharField(default='Unknown', max_length=50)),
                ('full_info', models.JSONField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmartPlugData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_data', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='smartPlug_devices.smartplug')),
            ],
        ),
    ]
