# Generated by Django 4.2.23 on 2025-06-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartPlug_devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartplug',
            name='online',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartplug',
            name='productName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='smartplugdata',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartplugdata',
            name='current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartplugdata',
            name='freq',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartplugdata',
            name='switchStatus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartplugdata',
            name='timeZone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartplugdata',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartplugdata',
            name='updateTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartplugdata',
            name='utcTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartplugdata',
            name='volt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartplugdata',
            name='watts',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
