# Generated by Django 4.2.23 on 2025-06-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartPlug_devices', '0002_smartplug_online_smartplug_productname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartplugdata',
            name='eatTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
