# Generated by Django 4.2.23 on 2025-08-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartPlug_devices', '0003_smartplugdata_eattime'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartplugdata',
            name='is_aggregated',
            field=models.BooleanField(default=False),
        ),
    ]
