# Generated by Django 4.2.23 on 2025-08-03 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartPlug_devices', '0004_smartplugdata_is_aggregated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPlugDataAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(default='Ecoflow', max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('metered_at', models.DateTimeField()),
                ('interval_seconds', models.IntegerField(default=600)),
                ('phase', models.CharField(default='1', max_length=10)),
                ('voltage_v', models.FloatField(blank=True, null=True)),
                ('current_a', models.FloatField(blank=True, null=True)),
                ('frequency_hz', models.FloatField(blank=True, null=True)),
                ('power_w', models.FloatField(blank=True, null=True)),
                ('power_factor', models.FloatField(blank=True, default=1.0, null=True)),
                ('energy_interval_wh', models.FloatField(blank=True, null=True)),
                ('energy_lifetime_wh', models.FloatField(blank=True, null=True)),
                ('billing_cycle_start_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='smartPlug_devices.smartplug')),
            ],
        ),
    ]
