# Generated by Django 4.2.23 on 2025-08-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartPlug_devices', '0005_smartplugdataaggregate'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartplugdataaggregate',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartplugdataaggregate',
            name='switchStatus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartplugdataaggregate',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
