# Generated by Django 4.2.23 on 2025-08-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartPlug_devices', '0006_smartplugdataaggregate_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartplugdata',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
