# Generated by Django 4.2.23 on 2025-08-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartPlug_devices', '0007_smartplugdata_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartplugdata',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
