# Generated by Django 4.2.23 on 2025-08-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartPlug_devices', '0008_alter_smartplugdata_serial_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartplugdata',
            old_name='current',
            new_name='current_raw',
        ),
    ]
