# Generated by Django 4.2.23 on 2025-08-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartPlug_devices', '0009_rename_current_smartplugdata_current_raw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartplugdata',
            old_name='current_raw',
            new_name='current',
        ),
    ]
