# Generated by Django 4.2.23 on 2025-08-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartPlug_devices', '0010_rename_current_raw_smartplugdata_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartplugdata',
            name='current_raw',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
