# Generated by Django 4.2.23 on 2025-08-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartPlug_devices', '0011_smartplugdata_current_raw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartplugdata',
            name='current_raw',
        ),
        migrations.AlterField(
            model_name='smartplugdata',
            name='eatTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
