# Generated by Django 4.2.23 on 2025-08-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartPlug_devices', '0012_remove_smartplugdata_current_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartplugdataaggregate',
            name='is_pushed',
            field=models.BooleanField(default=False),
        ),
    ]
